### ISSUE TITLE
Session restore freeze (realized this repo is a mirror, ignore)

### ISSUE THREAD

**Issue by nitrate92** [cdesktopenv/cde#2]
Every time I attempt to restore the "Current" session, my Arch VM freezes at this screen. Only the "Home" session lets me in, and nothing gets saved within it.
![image](https://github.com/cdesktopenv/cde/assets/46730268/1c07f2c6-345c-42f1-abe1-073d11ba130e)
Neofetch output:
![image](https://github.com/cdesktopenv/cde/assets/46730268/d6503988-39d6-4a18-a518-879df8f806bc)
uname -a output:
![image](https://github.com/cdesktopenv/cde/assets/46730268/25580832-e655-4afe-8dfc-9d26361893f4)

**Comment by unix-junkie** [comment]
@nitrate92, thank you for your bug report. This is an unofficial mirror of the Git repository hosted at SourceForge — as you can see, it's not even updated regularly.

I suggest you contact CDE developers using the official [bug tracker](https://sourceforge.net/p/cdesktopenv/tickets/).
